version: "3.9"

services:
  captcha-the-bot:
    container_name: captcha-the-bot
    build:
      context: .
      target: dev
    volumes:
      - "./:/captcha-the-bot"
    env_file:
      - .env
    ports:
      - "8080:8080"
